### ISSUE TITLE
is it possible to register https link while local version uses ssh?

### ISSUE THREAD

**Issue by schlichtanders** [GunnarFarneback/LocalRegistry.jl#2]
Hi,

thanks a lot for this lovely package. I stumble upon the case that I myself uses ssh keys to connect to my git, however I want to have the option that my registered packages refer to the repository via https.

Concretely two scenarios:
- I develop a private package, then I locally have ssh keys and also want to deploy with ssh keys
- I develop a public package, then locally I still want to use ssh keys but deployed should be the https variant

Is this already possible?
If not, can a flag be added to `register` to support this?

**Comment by GunnarFarneback** [comment]
From a registry point of view there is space to store exactly one URL, so there is nothing `register` can do to support alternative protocols.

However, there are some other mechanisms that can be used to support users without ssh keys:
* `Pkg.setprotocol!` is designed exactly for this purpose but I'm not sure to what extent it's able to translate between protocols for more exotic repository hosts than github.
* Even if you have an https URL in the registry, you can provide an explicit ssh URL to `Pkg.develop` to set up your development environment.
* From Julia 1.4 the [PkgServer](https://github.com/JuliaPackaging/PkgServer.jl) technology will provide an alternative means of deploying packages, which doesn't involve git at all. It may take a while before this is a convenient solution for private packages though.

**Comment by schlichtanders** [comment]
Hi @GunnarFarneback  thanks for your answer, I think we slightly misunderstood each other.

Currently, If I call
```
using MyPackage
register(MyPackage, "MyRegistry")
```
`register` will just overwrite the repository url with whatever is linked in the dev checkout of ``MyPackage``. This is always ``ssh`` for me, and hence it always overwrites the repostiory url to use ssh, even if I changed it to https version, as I wanted to have it public.

it would be nice to have ``register(MyPackage, "MyRegistry", https_repository=true)``or something similar, which will get the repository url (ssh) and try to transform it into a https reference and uses that.

**Comment by GunnarFarneback** [comment]
Right, this is currently being overly helpful in finding repository URLs. You can work around it by registering with an explicit `repo` keyword argument pointing to your preferred deployment URL.

However, changing URL is an atypical thing to do when you register a package. The default should be to keep the registered URL and only look up the `git remote` when registering a new package. Changing URL should only be possible with an explicit argument. I'll fix this after refactoring to use the revamped RegistryTools code.

**Comment by GunnarFarneback** [comment]
Addressed in #4.

**Comment by GunnarFarneback** [comment]
Closed by #4.
