### ISSUE TITLE
Incorrect compat entry for mixed range and normal version specifiers

### ISSUE THREAD

**Issue by dalum** [GunnarFarneback/LocalRegistry.jl#20]
Ran into this issue today, where a package had defined deps as:
```toml
MyPackage = "0.1.6 - 0.1.7, 0.2"
```
This lead to the following `Compat.toml` being generated:
```toml
MyPackage = "[\"0.1.6-0.1.7\", \"0.2\"]"
```
which gives a parse error, and broke the entire registry.  It required manual fixing, and the correct line should be:
```toml
MyPackage = ["0.1.6-0.1.7", "0.2"]
```
This might be an issue in RegistryTools.jl, but I couldn't immediately identify what should be changed to fix it, so filing an issue here instead.

**Comment by GunnarFarneback** [comment]
Looks like it is the same issue as https://github.com/JuliaRegistries/RegistryTools.jl/issues/48.
