### ISSUE TITLE
Is it possible to host a registry with LocalRegistry.jl?

### ISSUE THREAD

**Issue by MasFlam** [GunnarFarneback/LocalRegistry.jl#27]
I have a server where I'd like to host a Pkg registry for my projects. Is this package suited for remote repositories too, or can you only use it on the machine its on?

**Comment by GunnarFarneback** [comment]
The normal mode of operation is to host your registry on a server so it can be used by multiple people. The package is agnostic to git hosting services though, so it's up to you to create the remote repository and hook it up to the registry created/maintained by LocalRegistry.

**Comment by MasFlam** [comment]
Thanks!
