### ISSUE TITLE
Error message when package repo is dirty

### ISSUE THREAD

**Issue by baggepinnen** [GunnarFarneback/LocalRegistry.jl#28]
Thanks for this awesome package! I just started using it and noticed that there is an error message when the repo to a package I'm trying to register is dirty. This is very welcome! However, the message says that the *registry* is dirty rather than the package I'm registering:
```julia
julia> register("ClampingID", "CbRegistry")
ERROR: Package directory is dirty. Stash or commit files.
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
```
maybe the message could indicate if it's the package or the registry being dirty?

**Comment by GunnarFarneback** [comment]
I believe these lines do so: https://github.com/GunnarFarneback/LocalRegistry.jl/blob/26debaac21c87fb1409336e5f25d25cf6117cab4/src/LocalRegistry.jl#L156-L165

**Comment by baggepinnen** [comment]
Wow, I must have been very tired or something, even the message I reproduced in the issue says "package is dirty". I'm sorry for the noise 😕
