### ISSUE TITLE
GitError(Code:ERROR, Class:Net, Unsupported URL protocol)

### ISSUE THREAD

**Issue by BambOoxX** [GunnarFarneback/LocalRegistry.jl#34]
I am opening this issue here in addition to the more general https://github.com/JuliaLang/Pkg.jl/issues/1510.

After successfully creating and pushing a local registry on a private NAS server, I could not add it on another machine. 
The registry was created on a julia 1.6.0 install and the clone was attempted on a julia 1.5.4.

The call signature is after some redaction
```
(@v1.5) pkg> registry add \\nas_address\Git\Julia_Registry.git
    Cloning registry from "\\nas_address\Git\Julia_Registry.git"
ERROR: failed to clone from \\nas_address\Git\Julia_Registry.git, error: GitError(Code:ERROR, Class:Net, unsupported URL protocol)
```
This may be unrelated to `LocalRegistry` but I prefer to track it here too for potential help to other users.

**Comment by GunnarFarneback** [comment]
For reference this was also discussed in https://discourse.julialang.org/t/creating-a-custom-registry/28007/16?u=gunnarfarneback.

Did you solve the problem?

**Comment by BambOoxX** [comment]
@GunnarFarneback Yes I tested it yesterday and managed to solve the issue. 
On our case, it was that the local user was not logged on the NAS server, forbidding git to push / pull from it. 
Also, we used the `Pkg.Registry.add(PackageSpec(url=...))` syntax so as to reduce parsing errors.
Thanks for the help.
