### ISSUE TITLE
Can't push to registry

### ISSUE THREAD

**Issue by jonniedie** [GunnarFarneback/LocalRegistry.jl#37]
I followed the instructions in the README to set up a registry called "JuliaToolsRegistry". When I try to register a package to it, however, it gives me the error that I can't push to a non-bare repository.
```
remote: error: refusing to update checked out branch: refs/heads/master
remote: error: By default, updating the current branch in a non-bare repository
remote: is denied, because it will make the index and work tree inconsistent
remote: with what you pushed, and will require 'git reset --hard' to match
remote: the work tree to HEAD.
``` 
I tried manually setting it up as a bare repository instead, but then I get the error that it can't find the "Registry.toml" file.

**Comment by GunnarFarneback** [comment]
I'd need more details to say anything for sure but the idea is to have a remote repository from which the registry can be cloned by anyone who uses it and a local working copy in your `.julia` depot which your Julia can use. The remote repository could e.g. be on Github or some other other git hosting service but it could also be a repository on your own computer. This should indeed be a bare repository. The local working copy should normally be in your `.julia/registries` directory, in this case `.julia/registries/JuliaToolsRegistry` and should not be a bare repository.

So the recommended workflow would be to create a repository on Github, or some other hosting site, or a bare repository locally. Then you run `create_registry("JuliaToolsRegistry", "URL_TO_REPO"). This will create a non-bare repository in `.julia/registries/JuliaToolsRegistry` and set up `URL_TO_REPO` as remote url.

If you only want to have your registry in `.julia/registries/JuliaToolsRegistry` and not share it with anybody that's also possible. In that case you need to provide a fake remote url to `create_registry` and run `register` with the keyword argument `push=false`. (This was changed in LocalRegistry 0.4; before that `push=false` was the default.)

**Comment by jonniedie** [comment]
Oh, okay, thanks. It looks like I got it working, but I had to do `git push --set-upstream origin master` at the `.julia/registries/JuliaToolsRegistry` location. Does that sound right?

**Comment by GunnarFarneback** [comment]
If you use the `push=true` option for `create_registry`, this line should do it for you: https://github.com/GunnarFarneback/LocalRegistry.jl/blob/50b673338abc194ce5df667140d1d52863ef7d74/src/LocalRegistry.jl#L79-L81

Otherwise you need to do that yourself, yes.
