### ISSUE TITLE
Can't publish to github

### ISSUE THREAD

**Issue by fonsp** [GunnarFarneback/LocalRegistry.jl#39]
Hi!

I used `create_registry` to create a local repository, and then clicked the "Publish" button on github desktop to try to put it on github.com. This didn't work:

![image](https://user-images.githubusercontent.com/6933510/121002312-7f4c7c80-c78c-11eb-82c6-9b11b6c10bdf.png)

**Comment by GunnarFarneback** [comment]
I have never used the github desktop and have no idea what the "Publish" button is supposed to do. However, LocalRegistry only creates the repository locally and whatever steps are needed to create the remote repository must be done by other means.

**Comment by fonsp** [comment]
I worked around the problem by removing the `.git` directory. Perhaps the overlap of people who use LocalRegistry.jl and those who never use the `git` command line is too small to worry about :)
