### ISSUE TITLE
Automatically check out dummy branch when modifying a repo

### ISSUE THREAD

**Issue by jakobnissen** [GunnarFarneback/LocalRegistry.jl#40]
When modifying a local repo, just created, I get an error. This happens because LocalRegistry.jl tries to push to the original repo, and you cannot push to the currently checked out branch of the repo.

This could be solved a number of ways. Automatically setting `git config --bool core.bare true` in new repositories. Or automatically create a dummy branch and switch to it when necessary.

**Comment by GunnarFarneback** [comment]
Can you describe more exactly what you did? I suspect it was something unintended and that the documentation might need some clarification.

**Comment by GunnarFarneback** [comment]
From googling it seems like you also have the option to configure `receive.denyCurrentBranch` to `updateInstead` but the intention is that the remote should be bare and it frankly didn't occur to me that people would consider using non-bare repositories upstream. For that case your best current option is to `register` with `push = false` and juggle with branches on your own.

I do have plans to add the option to push to custom branches, but with the purpose to allow PR-based workflows. I haven't needed it myself yet though.

**Comment by jakobnissen** [comment]
It is completely fine that the repo should be bare. The issue is that it is not created as bare using `LocalRegistry`, it is not documented that it should be bare, and it is not checked whether it is bare when pushing. For me the issue was that I didn't know what a bare repo was, and so experienced a (to me) obscure error when using LocalRegistry.

Perhaps that can be some actionable points?:
* Initialize the repo as base with `create_registry`
* Document the repo needs to be bare
* If possible, check if the repo is bare when committing to it, and throw an informative error if it isn't

**Comment by GunnarFarneback** [comment]
> * Initialize the repo as bare with create_registry

`create_registry` is intended to create a checked out registry so it shouldn't be bare. The `repo` argument should point to a bare upstream though.

> * Document the repo needs to be bare

Yes, this should be documented. 

> * If possible, check if the repo is bare when committing to it, and throw an informative error if it isn't

This is a good idea if it can be done sufficiently easily, robustly and is not unduly slow.

Not exactly related to this issue, but the work in progress tutorial https://github.com/GunnarFarneback/LocalRegistry.jl/blob/tutorial/docs/tutorials/create_registry_github.md may help out a bit as well.

**Comment by jakobnissen** [comment]
> `create_registry` is intended to create a checked out registry so it shouldn't be bare. The repo argument should point to a bare upstream though.

Ah. Okay, so you need to point to an empty git repository if it's local? That would be nice to add in the docs :)
