### ISSUE TITLE
Cannot add any package after adding private registry within an empty environment

### ISSUE THREAD

**Issue by sairus7** [GunnarFarneback/LocalRegistry.jl#46]
If I add a private registry (`]registry add ...`) to a fresh system with a completely empty environment with no packages installed, then Julia cannot install any other public or private packages - it just says `Cannot find name corresponding to UUID`
To fix this, I need to remove private registry, then install any public package to General registry (e.g. `]add ArgParse`), then add private registry again, and then it works fine.

**Comment by GunnarFarneback** [comment]
The easiest solution is to do `]registry add General ...`  to install both General and your own registry at the same time.
There's not so much LocalRegistry can do about this except possibly mention it somewhere in the documentation.
