### ISSUE TITLE
On Julia 1.8.0-DEV, LocalRegistry restricted to v0.3.2

### ISSUE THREAD

**Issue by BioTurboNick** [GunnarFarneback/LocalRegistry.jl#50]
Due to compat bounds, attempting to install LocalRegistry on Julia 1.8.0-DEV leads to a very old version being installed, v0.3.2.

I'm assuming this is just because v0.3.2 has an open-ended compatibility bound.

Would it be better to make the bounds open-ended? If people should be careful about using it on the nightly builds, perhaps a warning could be produced instead?

**Comment by GunnarFarneback** [comment]
LocalRegistry relies too much on the Pkg internals for open-ended compatibility to be credible but I acknowledge there are drawbacks to upper-bounding it too. The registry definitely needs to be retro-capped for the oldest versions. I suspect the best solution is to keep master open-ended and refer Julia nightly users to that, but it will take some discipline to get that right.

**Comment by GunnarFarneback** [comment]
> The registry definitely needs to be retro-capped for the oldest versions.

https://github.com/JuliaRegistries/General/pull/55389

**Comment by GunnarFarneback** [comment]
I've bumped master to 1.8. I don't really trust myself to be consistent if I try to have only master unbounded, so I'll see if this will actually cause problems. At least Julia master shouldn't pull in an old version anymore.
