### ISSUE TITLE
Allow creation of registries with default branches other than `master`

### ISSUE THREAD

**Issue by jonniedie** [GunnarFarneback/LocalRegistry.jl#54]
[This line](https://github.com/GunnarFarneback/LocalRegistry.jl/blob/fb3e9160c73eb1523a4a405d32a465d3b99017eb/src/LocalRegistry.jl#L81) is hard-coded to use `master`, but it is becoming more popular to have default branches other than `master`. Is there a way to get the default branch name and use that?

**Comment by GunnarFarneback** [comment]
The easy workaround is obviously not to use `push = true` in the call and do the push to your branch of choice yourself.

As for getting the default branch name I remember having trouble finding a nice solution in the past, but it could be that I didn't look hard enough.
