### ISSUE TITLE
Support for packages in subdirectories of repositories

### ISSUE THREAD

**Issue by GunnarFarneback** [GunnarFarneback/LocalRegistry.jl#8]
Currently packages can only be registered if they live at the top level of a git repository. This is quite limiting if you have a git repository where a Julia package is only a part of the functionality or if you want to have multiple packages in the same repository.

The package manager itself has partial support for packages in subdirectories as described in https://github.com/JuliaLang/Pkg.jl/issues/1251. There is also a somewhat stalled [PR](https://github.com/JuliaLang/Pkg.jl/pull/1422) to improve the support. Even at the current state it should be possible and useful to add support for this to LocalRegistry.

**Comment by fingolfin** [comment]
Note that https://github.com/JuliaLang/Pkg.jl/pull/1422 has now been merged. Yay!
